[package]
name = "human-passport"
version = "0.12.0"
edition = "2021"

[dependencies]
human-passport-core = { path = "core" }
human-passport-methods = { path = "methods" }
rand = "0.8"
risc0-zkvm = "1.0.5"
bincode = "1.3.3"
serde_json = "1.0.127"
anyhow = "1.0.86"
